name: Build Slides

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
        matrix:
          node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: Jaid/action-npm-install@v1.2.4

    - name: Prepare build
      run: yarn run predeploy

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.6.4
      with:
        publish_dir: ./dist
        github_token: ${{ secrets.GITHUB_TOKEN }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: ${{ github.event.head_commit.message }}
